### PR TITLE
Map add

### PR DESCRIPTION
**Pull request by chhipanikhil9**
Nit trichy Map component has been added.

### CODE REVIEW

**Comment by 109-Vivek** [comment]
image
Showing location at wrong places
Its showing hostel and messes outside NITT 
Try fixing this

**Review by chhipanikhil9 — COMMENTED** [review]
Location has been updated

**Review by chhipanikhil9 — COMMENTED** [review]
Hostels added and center updated

**Review by 109-Vivek — APPROVED** [review]
Working but some locaitons has to added
But can be done later

**Pull request merged**
